name: ci

on:
  push:
    branches:
      - 'db-api-docker'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ciscowkang
          password: 23Dianyushan$
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/photoprism/jammy/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ciscowkang/photoprism-db-api-202300507
      -
        name: Build and push demo
        id: docker_build_demo
        uses: docker/build-push-action@v2
        with:
          file: ./docker/demo/Dockerfile
          push: true
          tags: ciscowkang/photoprism-db-api-demo-202300507
